[package]
id = "wqkvthxjifxdwgi4hc4efmtjct6tljbw"
name = "Console [WIP]"
description = "A Rhai-based console for interacting with the world and other packages."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Tool" }
ambient_version = "0.3.2-nightly-2023-11-27"

[messages.ConsoleServerInput.fields]
input = "String"

[messages.ConsoleServerOutput.fields]
text = "String"
ty = "U8"
is_server = "Bool"
