[package]
id = "zzcyk2wlcelbpd25bzsjffzdpjmjsnkl"
name = "Test Case 588"
version = "0.3.2-nightly-2023-11-27"
description = "Reproduces https://github.com/AmbientRun/Ambient/issues/588"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/testcases/588-prefab-despawn-panic"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
