[package]
id = "n7xfnlfzdmnvj7bqasfdhqftbtdi27ah"
name = "Editor Schema"
version = "0.3.2-nightly-2023-11-27"
description = "Schema for the editor."
content = { type = "Asset", schema = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[components]
# Player components
in_editor = { type = "Bool", attributes = ["Networked", "Debuggable"] }

[messages.EditorLoad]
description = "Sent by the editor when it has loaded to signal to other modules to add themselves."
fields = {}

[messages.EditorMenuBarAdd]
description = "Sent by other modules to add themselves to the editor's menubar."
fields = { name = "String" }

[messages.EditorMenuBarClick]
description = "Sent by the editor when a menu item is clicked."
fields = { name = "String" }
