[package]
id = "jm77qrzni2f4gied5fy54bia2lqmhebn"
name = "Physics"
description = "Make things collide and interact in a physically realistic way."
version = "0.3.2-nightly-2023-11-24"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/physics/basics"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[messages.Bonk]
description = "Collision between two objects."
fields = { emitter = "EntityId", listener = "EntityId" }

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
