[package]
id = "n7a4j7htvenss35tsnfvegbhxuwij5il"
name = "Base Assets [WIP]"
description = "Assets used by examples."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", models = true }
ambient_version = "0.3.2-nightly-2023-11-27"
