[package]
id = "roosvvawp6sjvlolokk5qyafl5vp2su7"
name = "Tangent Spawner: Vehicle"
description = "Handles vehicle spawning for Tangent."
version = "0.3.2-nightly-2023-11-25"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2023-11-25"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", deployment = "5Dxfql36E5hkktqsE0Eabx" }

nameplates = { path = "../../../../std/nameplates", deployment = "72DSQZF3Epi0GCy9JUmnAh" }

[messages.VehicleSpawn]
name = "Vehicle Spawn"
description = "Spawns the vehicle from the given definition."
fields = { def_id = "EntityId", position = "Vec3", rotation = { container_type = "Option", element_type = "Quat" }, driver_id = { container_type = "Option", element_type = "EntityId" } }
