[package]
name = "ambient_package_semantic"
edition = "2021"
description = "Semantic analysis for the Ambient package manifests"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
ambient_package = { path = "../package" , version = "0.3.2-nightly-2023-12-28" }
ambient_shared_types = { path = "../shared_types" , version = "0.3.2-nightly-2023-12-28" }
ambient_schema = { path = "../../schema" , version = "0.3.2-nightly-2023-12-28" }
ambient_std = { path = "../std" , version = "0.3.2-nightly-2023-12-28" }
ambient_dirs = { path = "../dirs" , version = "0.3.2-nightly-2023-12-28" }

anyhow = { workspace = true }
ulid = { workspace = true }
glam = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
paste = { workspace = true }
data-encoding = { workspace = true }
indexmap = { workspace = true }
async-recursion = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
