[package]
id = "pdvnxkqc5xuwanvxe2yxasswtk23pqij"
name = "Line"
description = "Draw a line in 3D space."
version = "0.3.2-nightly-2024-02-02"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/rendering/line"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-02-02"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
