[package]
name = "ambient_input"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient input functionality. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-11-26" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-11-26" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-11-26" }
ambient_shared_types = { path = "../../shared_crates/shared_types", features = ["native"] , version = "0.3.2-nightly-2023-11-26" }
winit = { workspace = true }
glam = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
flume = { workspace = true }
