[package]
id = "nd2mwrslb3iyo2bw4jmwcbkuo4mtuyfr"
name = "Decals"
description = "Render 'stickers' onto any surface."
version = "0.3.2-nightly-2023-11-23"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/decals"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-23"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera" , deployment = "5LYimSMVCEG1d8FIRz7yXj" }
