[package]
id = "xgafi5ckk5vhxscb6tqubfvy2fwfyqxo"
name = "Tangent Behavior: Character"
description = "Implements the character behavior for Tangent."
version = "0.3.2-nightly-2023-11-25"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2023-11-25"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", deployment = "5Dxfql36E5hkktqsE0Eabx" }
game_object = { path = "../../../../schemas/game_object", deployment = "TFYhFc5wKkplokwUm1uQN" }
unit_schema = { path = "../../../../schemas/unit", deployment = "hfv4W9UuED197vKDfol7g" }

base_assets = { path = "../../../../std/base_assets", deployment = "8HCtBKdJiEHCrSR52iTRZ" }
character_animation = { path = "../../../../std/character_animation", deployment = "1gJ1BGZMYz2k6SQwHVONG4" }
character_movement = { path = "../../../../std/character_movement", deployment = "2TMMtfgQwAplpQtmAfyzci" }
