[package]
id = "d563xtcr72ovuuhfkvsgag6z3wiy5jwr"
name = "Input"
description = "Read keyboard and mouse inputs from the player."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/input"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
