
[package]
name = "ambient_world_audio"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient world audio. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.2-nightly-2024-01-07" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2024-01-07" }
ambient_app = { path = "../app" , version = "0.3.2-nightly-2024-01-07" }
ambient_ui_native = { path = "../ui_native" , version = "0.3.2-nightly-2024-01-07" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2024-01-07" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2024-01-07" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2024-01-07" }
ambient_audio = { path = "../audio" , version = "0.3.2-nightly-2024-01-07" }
# ambient_network = { path = "../network" , version = "0.2.1" }
parking_lot = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
flume = { workspace = true }
rand = { workspace = true }
rand_chacha = "0.3.1"
itertools = { workspace = true }
glam = { workspace = true }
tracing = { workspace = true }
derive_more = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2024-01-07" }
ambient_primitives = { path = "../primitives" , version = "0.3.2-nightly-2024-01-07" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2024-01-07" }

[features]
hotload-includes = ['ambient_native_std/hotload-includes']
