[package]
id = "xz2ip2ptvxprurqwaiv2nncabcrmml2w"
name = "Clientside"
description = "How to use clientside code."
version = "0.3.2-nightly-2023-11-23"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/clientside"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-23"

[components]
grid_side_length = { name = "Grid Side Length", description = "The length of a grid side, ignoring the centre (i.e. if this is 10, the total axis length is 21)", type = "I32", attributes = [
    "Networked",
    "Debuggable",
] }
grid_position = { name = "Grid Position", description = "The position of the cell on the grid", type = "Ivec2", attributes = [
    "Networked",
    "Debuggable",
] }

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
