[package]
name = "ambient_gpu_ecs"
edition = "2021"
version.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-12-04" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2023-12-04" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-04" }
derive_more = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
wgpu = { workspace = true }
parking_lot = { workspace = true }
profiling = { workspace = true }
lazy_static = { workspace = true }
tracing = { workspace = true }
bytemuck = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-12-04" }
tracing-subscriber = { workspace = true }
