[package]
id = "tijz7x6fimbgu24sbbtp4nllhfxbgblp"
name = "Orbit Camera"
description = "Implements a clientside-only orbit camera. Very basic and not interoperable with other cameras; its primary purpose is for demos. Note that it will automatically add a focusable game element that may be incompatible with `hide_cursor` and similar packages."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[components]
is_orbit_camera = { type = "Empty", attributes = ["Debuggable", "Networked"] }
camera_angle = { type = "Vec2", description = "Camera angle specified in radians; x = yaw, y = pitch", attributes = [
    "Debuggable",
    "Networked",
] }
camera_distance = { type = "F32", description = "Camera distance specified in meters", attributes = [
    "Debuggable",
    "Networked",
] }

[concepts.OrbitCamera]
name = "Orbit Camera"
description = "An orbit camera."
[concepts.OrbitCamera.components.required]
is_orbit_camera = { suggested = {} }
[concepts.OrbitCamera.components.optional]
camera_angle = {}
camera_distance = {}
"ambient_core::transform::lookat_target" = {}
