[package]
id = "ib2djsnjew5tb2k5igq6le7rzjdwlvhq"
name = "Material overriding"
description = "Combining a model with a custom material override in the pipeline."
version = "0.3.2-nightly-2023-11-24"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/material_overriding"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[components.is_the_best]
type = "Bool"
name = "Is The Best"
description = "Declares whether or not the entity this is attached is the best."
attributes = ["Networked", "Debuggable"]

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "2o485Le57deXsEYhFu4lmf" }
