[package]
name = "ambient_gizmos"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient gizmos. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-11-23" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-11-23" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2023-11-23" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-11-23" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2023-11-23" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2023-11-23" }
dashmap = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
wgpu = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
once_cell = "1.18.0"
profiling = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" , version = "0.3.2-nightly-2023-11-23" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2023-11-23" }
ambient_std = { path = "../../shared_crates/std" , version = "0.3.2-nightly-2023-11-23" }

[features]
hotload-includes = ['ambient_native_std/hotload-includes']
