[package]
name = "ambient_primitives"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient primitives. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-12-03" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2023-12-03" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-12-03" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-03" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2023-12-03" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2023-12-03" }
glam = { workspace = true }
