
[package]
name = "ambient_physics"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient physics. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs", version = "0.3.2-nightly-2023-12-19" }
ambient_native_std = { path = "../native_std", version = "0.3.2-nightly-2023-12-19" }
ambient_core = { path = "../core", version = "0.3.2-nightly-2023-12-19" }
ambient_meshes = { path = "../meshes", version = "0.3.2-nightly-2023-12-19" }
ambient_network = { path = "../network", version = "0.3.2-nightly-2023-12-19" }
ambient_gizmos = { path = "../gizmos", version = "0.3.2-nightly-2023-12-19" }
ambient_model = { path = "../model", version = "0.3.2-nightly-2023-12-19" }
ambient_primitives = { path = "../primitives", version = "0.3.2-nightly-2023-12-19" }

physxx = { path = "../../libs/physxx", version = "0.3.2-nightly-2023-12-19" }
serde = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
profiling = { workspace = true }
ordered-float = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" , version = "0.3.2-nightly-2023-12-19" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2023-12-19" }
ambient_primitives = { path = "../primitives" , version = "0.3.2-nightly-2023-12-19" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2023-12-19" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2023-12-19" }
