[package]
name = "ambient_prefab"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient entity prefab implementation. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs", version = "0.3.2-nightly-2024-01-02" }
ambient_sys = { path = "../sys", version = "0.3.2-nightly-2024-01-02" }
ambient_core = { path = "../core", version = "0.3.2-nightly-2024-01-02" }
ambient_model = { path = "../model", version = "0.3.2-nightly-2024-01-02" }
ambient_rpc = { path = "../rpc", version = "0.3.2-nightly-2024-01-02" }
ambient_native_std = { path = "../native_std", version = "0.3.2-nightly-2024-01-02" }
ambient_decals = { path = "../decals", version = "0.3.2-nightly-2024-01-02" }
tokio = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
ambient_physics = { path = "../physics", version = "0.3.2-nightly-2024-01-02" }
