[package]
name = "ambient_procedurals"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient procedural generation functionality."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2024-01-11" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2024-01-11" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2024-01-11" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2024-01-11" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2024-01-11" }
ambient_shared_types = { path = "../../shared_crates/shared_types" , version = "0.3.2-nightly-2024-01-11" }

wgpu = { workspace = true }
paste = { workspace = true }
