[package]
id = "k7svgbw5j6orlwzj45koeownlodsdbth"
name = "Kenney's Digital Audio"
authors = ["Kenney"]
description = "https://www.kenney.nl/assets/digital-audio for Ambient. (Uploaded by Ambient, not Kenney.)"
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", audio = true }
ambient_version = "0.3.2-nightly-2023-11-27"
