[package]
name = "ambient_renderer"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient renderer. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.2-nightly-2023-12-20" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-20" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-12-20" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2023-12-20" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-12-20" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2023-12-20" }
ambient_gpu_ecs = { path = "../gpu_ecs" , version = "0.3.2-nightly-2023-12-20" }
ambient_settings = { path = "../settings" , version = "0.3.2-nightly-2023-12-20" }

ambient_color = { path = "../../libs/color", features = ["wgpu"] , version = "0.3.2-nightly-2023-12-20" }

as-any = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
ordered-float = { workspace = true }
serde = { workspace = true }
derive_more = { workspace = true }
profiling = { workspace = true }
bytemuck = { workspace = true }
smallvec = { workspace = true }
parking_lot = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" , version = "0.3.2-nightly-2023-12-20" }
ambient_gizmos = { path = "../gizmos" , version = "0.3.2-nightly-2023-12-20" }
ambient_model_import = { path = "../model_import" , version = "0.3.2-nightly-2023-12-20" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2023-12-20" }
ambient_primitives = { path = "../primitives" , version = "0.3.2-nightly-2023-12-20" }

ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2023-12-20" }
ambient_std = { path = "../../shared_crates/std" , version = "0.3.2-nightly-2023-12-20" }

env_logger = { workspace = true }
winit = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
hotload-includes = ['ambient_native_std/hotload-includes']
