[package]
id = "of4w7yibjeuokeyypqxmtgqklc6vthln"
name = "Messaging"
description = "Send and receive data across the network and to other modules."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/messaging"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[messages.Hello]
name = "Hello"
description = "Sent when a client joins the server, then sent back from the server"
fields = { text = "String", source_reliable = "Bool" }

[messages.HelloWithoutBody]
description = "Sent just to say hi"
fields = {}

[messages.Local]
description = "Sent until it's acknowledged"
fields = { text = "String" }
