[package]
name = "ambient_model_import"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient model importer. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_native_std = { path = "../native_std", version = "0.3.2-nightly-2023-12-16" }
ambient_core = { path = "../core", version = "0.3.2-nightly-2023-12-16" }
ambient_ecs = { path = "../ecs", version = "0.3.2-nightly-2023-12-16" }
ambient_gpu = { path = "../gpu", version = "0.3.2-nightly-2023-12-16" }
ambient_renderer = { path = "../renderer", version = "0.3.2-nightly-2023-12-16" }
ambient_physics = { path = "../physics", version = "0.3.2-nightly-2023-12-16" }
ambient_model = { path = "../model", version = "0.3.2-nightly-2023-12-16" }
ambient_animation = { path = "../animation", version = "0.3.2-nightly-2023-12-16" }
ambient_pipeline_types = { path = "../pipeline_types", version = "0.3.2-nightly-2023-12-16" }

physxx = { path = "../../libs/physxx", version = "0.3.2-nightly-2023-12-16" }
glam = { workspace = true }
env_logger = { workspace = true }
gltf = { workspace = true }
image = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
async-recursion = { workspace = true }
fbxcel = { workspace = true }
ordered-float = { workspace = true }
indexmap = { workspace = true }
tracing = { workspace = true }
relative-path = { workspace = true }
russimp = { workspace = true, optional = true }
convert_case = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" , version = "0.3.2-nightly-2023-12-16" }
ambient_gizmos = { path = "../gizmos" , version = "0.3.2-nightly-2023-12-16" }
ambient_primitives = { path = "../primitives" , version = "0.3.2-nightly-2023-12-16" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2023-12-16" }

ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2023-12-16" }
ambient_std = { path = "../../shared_crates/std" , version = "0.3.2-nightly-2023-12-16" }

winit = { workspace = true }
