[package]
id = "d4ctdtfmrwpccnqlb5pyu47tdah3rck5"
name = "Slider"
description = "Demonstration of various types of sliders for numbers."
version = "0.3.2-nightly-2024-01-01"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/slider"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-01"
