[package]
id = "sssnr4szjawggp2g6drtbubls74c5gwj"
name = "Generating pipeline.toml"
description = "Use code to generate an asset `pipeline.toml` file."
version = "0.3.2-nightly-2023-11-23"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/basic_model"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-23"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "4NVaupFsEeGK5Zk3QURBA9" }
