[package]
id = "mwrcsok65na7owrbdococ5sthr3ccskc"
name = "Tangent Schema"
version = "0.3.2-nightly-2023-11-23"
content = { type = "Asset", schema = true }
authors = ["philpax"]
ambient_version = "0.3.2-nightly-2023-11-23"

[dependencies]
game_object = { path = "../../../schemas/game_object", deployment = "TFYhFc5wKkplokwUm1uQN" }
unit = { path = "../../../schemas/unit" , deployment = "hfv4W9UuED197vKDfol7g" }

[components]
# Player
"player::vehicle_ref" = { type = "EntityId", name = "Player's Vehicle", description = "The player's vehicle", attributes = [
    "Networked",
    "Debuggable",
] }
"player::character_ref" = { type = "EntityId", name = "Player's Character", description = "The player's character", attributes = [
    "Networked",
    "Debuggable",
] }
"player::class_ref" = { type = "EntityId", name = "Class", description = "The player's class", attributes = [
    "Networked",
    "Debuggable",
] }

"player::input_direction" = { type = "Vec2", name = "Input Direction", description = "Input direction", attributes = [
    "Debuggable",
] }
"player::input_jump" = { type = "Bool", name = "Jump", description = "Jump", attributes = [
    "Debuggable",
] }
"player::input_fire" = { type = "Bool", name = "Fire", description = "Fire", attributes = [
    "Debuggable",
] }
"player::input_use" = { type = "Bool", name = "Use", description = "Use", attributes = [
    "Debuggable",
] }
"player::input_sprint" = { type = "Bool", name = "Sprint", description = "Sprint", attributes = [
    "Debuggable",
] }
"player::input_respawn" = { type = "Bool", name = "Respawn", description = "Respawn", attributes = [
    "Debuggable",
] }
"player::input_aim_direction" = { type = "Vec2", name = "Aim Direction", description = "Aim direction in degrees from the centre", attributes = [
    "Debuggable",
] }
"player::input_aim_ray_origin" = { type = "Vec3", name = "Aim Ray Origin", description = "Origin of the aim ray", attributes = [
    "Debuggable",
] }
"player::input_aim_ray_direction" = { type = "Vec3", name = "Aim Ray Direction", description = "Direction of the aim ray", attributes = [
    "Debuggable",
] }

# Player class
"player::class::is_class" = { type = "Empty", name = "Is Class", description = "Is a player class", attributes = [
    "Networked",
    "Debuggable",
] }
"player::class::name" = { type = "String", name = "Name", description = "Name of the player class", attributes = [
    "Networked",
    "Debuggable",
] }
"player::class::description" = { type = "String", name = "Description", description = "Description of the player class", attributes = [
    "Networked",
    "Debuggable",
] }
"player::class::icon_url" = { type = "String", name = "Icon URL", description = "URL of the icon for the player class", attributes = [
    "Networked",
    "Debuggable",
] }
"player::class::def_ref" = { type = "EntityId", name = "Class Definition Ref", description = "When attached to a class, indicates that it should draw its properties from this entity.", attributes = [
    "Networked",
    "Debuggable",
] }

# Character
"character::is_character" = { type = "Empty", name = "Is Character", description = "Is a player character", attributes = [
    "Networked",
    "Debuggable",
] }
"character::player_ref" = { type = "EntityId", name = "Character's Player", description = "The player controlling the character", attributes = [
    "Networked",
    "Debuggable",
] }
"character::last_use_time" = { type = "Duration", name = "Last Use Time", description = "The last time the player tried to use something", attributes = [
    "Networked",
    "Debuggable",
] }
"character::def_ref" = { type = "EntityId", name = "Character Definition Ref", description = "When attached to a character, indicates that it should draw its properties from this entity.", attributes = [
    "Networked",
    "Debuggable",
] }

"character::head::camera_ref" = { type = "EntityId", name = "Head Camera", description = "The camera attached to the character's head", attributes = [
    "Networked",
    "Debuggable",
] }

# Character def
"character::def::model_url" = { type = "String", name = "Model URL", description = "URL of the model for the character def", attributes = [
    "Networked",
    "Debuggable",
] }

# Vehicle def
"vehicle::def::thruster::offsets" = { type = { type = "Vec", element_type = "Vec2" }, name = "Thruster Offsets", description = "Offsets of the thrusters from the center of the vehicle", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::thruster::k_p" = { type = "F32", name = "Thruster K_p", description = "Proportional gain for the thrusters", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::thruster::k_d" = { type = "F32", name = "Thruster K_d", description = "Derivative gain for the thrusters", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::thruster::target" = { type = "F32", name = "Thruster Target Altitude", description = "Target altitude for the thrusters", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::thruster::max_strength" = { type = "F32", name = "Thruster Max Strength", description = "Maximum strength of the thrusters", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::input::forward_force" = { type = "F32", name = "Forward Force", description = "Forward force applied to the vehicle on input", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::input::backward_force" = { type = "F32", name = "Backward Force", description = "Backward force applied to the vehicle on input", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::input::forward_offset" = { type = "Vec2", name = "Forward Offset", description = "Offset of the forward force from the center of the vehicle. Typically at the back of the vehicle.", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::input::side_force" = { type = "F32", name = "Side Force", description = "Side force applied to the vehicle on input", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::input::side_offset" = { type = "Vec2", name = "Side Offset", description = "Offset of the side force from the center of the vehicle. Typically at the front of the vehicle.", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::input::jump_force" = { type = "F32", name = "Jump Force", description = "Jump force applied to the vehicle on input", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::input::pitch_strength" = { type = "F32", name = "Pitch Strength", description = "Strength of the pitch applied to the applicable thrusters of the vehicle on input", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::input::turning_strength" = { type = "F32", name = "Turning Strength", description = "Strength of the turning applied to the applicable thrusters of the vehicle on input", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::input::jump_timeout" = { type = "Duration", name = "Jump Timeout", description = "Timeout between jumps", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::input::aim_direction_limits" = { type = "Vec2", name = "Aim Direction Limits", description = "Limits of the aim direction in degrees from the centre", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::slowdown::linear_strength" = { type = "F32", name = "Linear Strength", description = "Strength of the linear slowdown applied to the vehicle", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::slowdown::angular_strength" = { type = "F32", name = "Angular Strength", description = "Strength of the angular slowdown applied to the vehicle", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::slowdown::angular_delay" = { type = "Duration", name = "Angular Delay", description = "Time to wait before applying angular slowdown", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::def::is_def" = { type = "Empty", name = "Is Def", description = "Is a vehicle def", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::name" = { type = "String", name = "Name", description = "Name of the vehicle def", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::model_url" = { type = "String", name = "Model URL", description = "URL of the model for the vehicle def", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def::model_scale" = { type = "F32", name = "Model Scale", description = "Scale of the model for the vehicle def", attributes = [
    "Networked",
    "Debuggable",
] }

# Vehicle
"vehicle::is_vehicle" = { type = "Empty", name = "Is Vehicle", description = "Is a vehicle", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::driver_ref" = { type = "EntityId", name = "Vehicle Driver", description = "A vehicle's driver, if present", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::def_ref" = { type = "EntityId", name = "Vehicle Definition Ref", description = "When attached to a vehicle entity, indicates that it should draw its properties from this entity.", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::aimable_weapon_refs" = { type = { type = "Vec", element_type = "EntityId" }, name = "Aimable Weapon Refs", description = "All aimable weapons for this vehicle. If present in this array, their rotations will be automatically updated to match the aim position. Assumes that the weapons are a child of the vehicle.", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::last_distances" = { type = { type = "Vec", element_type = "F32" }, name = "Last Distances", description = "Distances from the ground for each vehicle probe", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::last_jump_time" = { type = "Duration", name = "Last Jump Time", description = "The last time the player jumped", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::last_slowdown_time" = { type = "Duration", name = "Last Slowdown Time", description = "The last time the player's vehicle was slowed down", attributes = [
    "Networked",
    "Debuggable",
] }
"vehicle::last_upside_down_time" = { type = "Duration", name = "Last Upside Down Time", description = "The last time the player's vehicle was known to be upside down. Added when first detected, removed when no longer the case. Used to respawn the vehicle after some time.", attributes = [
    "Networked",
    "Debuggable",
] }

"vehicle::input_direction" = { type = "Vec2", name = "Input Direction", description = "Input direction", attributes = [
    "Debuggable",
] }
"vehicle::input_jump" = { type = "Bool", name = "Jump", description = "Jump", attributes = [
    "Debuggable",
] }
"vehicle::input_fire" = { type = "Bool", name = "Fire", description = "Fire", attributes = [
    "Debuggable",
] }
# Vehicle (server-only)
"vehicle::aim_position" = { type = "Vec3", name = "Aim Position", description = "Position of the aim target", attributes = [
    "Debuggable",
] }

# Vehicle (client-only)
"vehicle::client::speed_kph" = { type = "F32", name = "Speed (KPH)", description = "Speed of the vehicle in kilometers per hour." }

# Spawnpoint
"spawnpoint::is_spawnpoint" = { type = "Empty", name = "Is Spawnpoint", description = "Is a spawnpoint", attributes = [
    "Networked",
    "Debuggable",
] }
"spawnpoint::radius" = { type = "F32", name = "Radius", description = "Radius of the spawnpoint", attributes = [
    "Networked",
    "Debuggable",
] }

# Weapon
"weapon::fire" = { type = "Bool", name = "Fire", description = "When on, the weapon will attempt to fire.", attributes = [
    "Networked",
    "Debuggable",
] }

[concepts.PlayerClass]
name = "Player Class"
description = "A player class"
[concepts.PlayerClass.components.required]
"player::class::is_class" = {}
"player::class::name" = {}
"player::class::description" = {}
"player::class::icon_url" = {}
"player::class::def_ref" = {}

[concepts.Character]
name = "Character"
description = "A character with a physical representation"
[concepts.Character.components.required]
"ambient_core::transform::translation" = {}
"ambient_core::transform::rotation" = {}

"game_object::health" = {}
"game_object::max_health" = {}

"character::is_character" = {}
"character::player_ref" = {}
"character::def_ref" = {}
[concepts.Character.components.optional]
"character::last_use_time" = {}

[concepts.CharacterDef]
name = "Character Definition"
description = "Definition for a character"
[concepts.CharacterDef.components.required]
"game_object::max_health" = {}
"character::def::model_url" = {}

"unit::speed" = {}
"unit::run_speed_multiplier" = {}
"unit::strafe_speed_multiplier" = {}

[concepts.VehicleDef]
name = "Vehicle Definition"
description = "Definition for a vehicle"
[concepts.VehicleDef.components.required]
"ambient_core::physics::density" = {}
"ambient_core::physics::cube_collider" = {}

"game_object::max_health" = {}

"vehicle::def::thruster::offsets" = {}
"vehicle::def::thruster::k_p" = {}
"vehicle::def::thruster::k_d" = {}
"vehicle::def::thruster::target" = {}
"vehicle::def::thruster::max_strength" = {}

"vehicle::def::input::forward_force" = {}
"vehicle::def::input::backward_force" = {}
"vehicle::def::input::forward_offset" = {}

"vehicle::def::input::side_force" = {}
"vehicle::def::input::side_offset" = {}

"vehicle::def::input::jump_force" = {}

"vehicle::def::input::aim_direction_limits" = {}

"vehicle::def::input::pitch_strength" = {}
"vehicle::def::input::turning_strength" = {}

"vehicle::def::input::jump_timeout" = {}

"vehicle::def::slowdown::linear_strength" = {}
"vehicle::def::slowdown::angular_strength" = {}
"vehicle::def::slowdown::angular_delay" = {}

"vehicle::def::is_def" = {}
"vehicle::def::name" = {}
"vehicle::def::model_url" = {}
"vehicle::def::model_scale" = {}

[concepts.Vehicle]
name = "Vehicle"
description = "A vehicle with a physical representation"
[concepts.Vehicle.components.required]
"ambient_core::physics::linear_velocity" = {}
"ambient_core::physics::angular_velocity" = {}
"ambient_core::physics::physics_controlled" = {}
"ambient_core::physics::dynamic" = {}
"ambient_core::physics::density" = {}
"ambient_core::physics::cube_collider" = {}

"ambient_core::transform::local_to_world" = {}
"ambient_core::transform::translation" = {}
"ambient_core::transform::rotation" = {}

"game_object::health" = {}
"game_object::max_health" = {}

"vehicle::is_vehicle" = {}

"vehicle::last_distances" = {}
"vehicle::last_jump_time" = {}
"vehicle::last_slowdown_time" = {}
"vehicle::def_ref" = {}

"vehicle::input_direction" = {}
"vehicle::input_jump" = {}
"vehicle::input_fire" = {}
[concepts.Vehicle.components.optional]
"vehicle::driver_ref" = {}
"vehicle::last_upside_down_time" = {}
"vehicle::aim_position" = {}
"vehicle::aimable_weapon_refs" = {}

[concepts.Spawnpoint]
name = "Spawnpoint"
description = "A spawnpoint"
[concepts.Spawnpoint.components.required]
"spawnpoint::is_spawnpoint" = {}
"spawnpoint::radius" = {}
"ambient_core::transform::translation" = {}
"ambient_core::rendering::color" = {}
