
[package]
name = "ambient_editor_derive"
edition = "2021"
description = "A procedural macro to generate Ambient UI code for a struct or enum."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
pretty_assertions = { workspace = true }
syn = { workspace = true }
proc-macro-crate = { workspace = true }

[dev-dependencies]
ambient_ui_native = { path = "../../crates/ui_native" , version = "0.3.2-nightly-2024-01-05" }
pretty_assertions = "1.4"
