[package]
id = "thr5tsq3g3vvf7ilap2jfu6bpoyas53s"
name = "Tic Tac Toe"
description = "Aka five-in-a-row."
version = "0.3.2-nightly-2023-11-25"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/packages/games/tictactoe"
type = "Game"
content = { type = "Playable" }
ambient_version = "0.3.2-nightly-2023-11-25"

[components]
cells = { type = { type = "Vec", element_type = "EntityId" }, name = "Cells", description = "The cells in the game", attributes = [
    "Debuggable",
    "Networked",
] }
cell = { type = "I32", name = "Cell", description = "The ID of the cell this player is in", attributes = [
    "Debuggable",
    "Networked",
] }
owned_by = { type = "EntityId", name = "Owned By", description = "The ID of the player that owns this cell", attributes = [
    "Debuggable",
    "Networked",
] }

[messages.Input]
description = "The player's input"
[messages.Input.fields]
up = "Bool"
down = "Bool"
left = "Bool"
right = "Bool"
capture = "Bool"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera" , deployment = "5LYimSMVCEG1d8FIRz7yXj" }
