[package]
id = "cfi3occcjea6qqnvaktvsgumnwduqq55"
name = "Fog"
description = "Create a mystical ambience for your game with fog."
version = "0.3.2-nightly-2023-11-25"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/fog"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-25"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera" , deployment = "5LYimSMVCEG1d8FIRz7yXj" }
