[package]
id = "jkfalriqol5mtd7hxq7yssldubgpcf5o"
name = "animations"
version = "0.3.2-nightly-2023-11-24"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[dependencies]
base_assets = { path = "../../../packages/std/base_assets", deployment = "8HCtBKdJiEHCrSR52iTRZ" }
character_animation = { path = "../../../packages/std/character_animation", deployment = "1gJ1BGZMYz2k6SQwHVONG4" }
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
performance_bar = { path = "../../../packages/tools/performance_bar", deployment = "3mRrA6Vw2K3E9WFK2yjxXO" }
