[package]
name = "ambient_rect"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient rectangle definition. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-12-16" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-12-16" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2023-12-16" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2023-12-16" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2023-12-16" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-16" }
ambient_layout = { path = "../layout" , version = "0.3.2-nightly-2023-12-16" }
glam = { workspace = true }
wgpu = { workspace = true }
bytemuck = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
