[package]
id = "hvxms7i2px7krvkm23sxfjxsjqlcmtb5"
name = "Game Object"
description = "Schema for game objects."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", schema = true }
ambient_version = "0.3.2-nightly-2023-11-27"

[components]
health = { type = "F32", name = "Health", description = "This game object's health. \"Standard\" health is 100 HP.", attributes = [
    "Debuggable",
    "Networked",
] }
max_health = { type = "F32", name = "Max Health", description = "Maximum health of the object. 100 HP is \"standard.\"", attributes = [
    "Debuggable",
    "Networked",
] }

"player::control_of_entity" = { type = "EntityId", name = "Player's Control-of Entity", description = "The entity that this player is controlling.", attributes = [
    "Debuggable",
    "Networked",
] }
