[package]
id = "pdgdtcgm5fxbrhvdcliwz2eogtihrqo3"
name = "Dock Layout"
description = "Top-down layout."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/dock_layout"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
