[package]
name = "ambient_git_rev_init"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient git revision helper. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_git_rev = { path = "../git_rev", version = "0.3.2-nightly-2023-12-31" }
