[package]
id = "t5rzmpq5h7dwjkxe7zugthxlauvon5mp"
name = "Counter"
description = "A simple counter with state management."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/counter"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
