[package]
id = "clwaexkinp2lnxm2h6r4gznp6gqfrmne"
name = "Auto-editor"
description = "Automatically derive editor UI for structs and enums."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/auto_editor"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
