[package]
name = "App"
description = "High-level state relevant to the application (including the in-development Editor)."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-12-31"
ambient_version = "0.3.2-nightly-2023-12-31"

[components.cursor_position]
type = "Vec2"
name = "Cursor position"
description = "Absolute mouse cursor position in screen-space. This is the *logical* position. Multiply by the `window_scale_factor` to get the physical position."
attributes = ["MaybeResource", "Debuggable", "Networked"]

[components.delta_time]
type = "F32"
name = "Delta time"
description = "How long the previous tick took in seconds."
attributes = ["Debuggable", "Resource"]

[components.epoch_time]
type = "Duration"
name = "Epoch time"
description = "Time since epoch (Jan 1, 1970). Non_monotonic."
attributes = ["Debuggable", "Resource"]

[components.game_time]
type = "Duration"
name = "Game time"
description = "Time since the game was started. Monotonic."
attributes = ["Debuggable", "Resource"]

[components.element]
type = "String"
name = "Element"
description = """
The identifier of the `Element` that controls this entity.
This is automatically generated by `ElementTree`."""
attributes = ["Debuggable", "Networked"]

[components.element_unmanaged_children]
type = "Empty"
name = "Element unmanaged children"
description = "If this is set, the user is expected to manage the children of the `Element` themselves."
attributes = ["Debuggable", "Networked"]

[components.main_scene]
type = "Empty"
name = "Main scene"
description = "If attached, this entity belongs to the main scene."
attributes = ["Debuggable", "Networked", "Store"]

[components.map_seed]
type = "U64"
name = "Map seed"
description = "A random number seed for this map."
attributes = ["Debuggable", "Networked", "Store"]

[components.name]
type = "String"
name = "Name"
description = "A human-friendly name for this entity."
# name is MaybeResource as it can be used as part of the resources entity of a prefab
attributes = ["Debuggable", "Networked", "Store", "MaybeResource"]

[components.description]
type = "String"
name = "Description"
description = "A human-friendly description for this entity."
attributes = ["Debuggable", "Networked", "Store"]

[components.main_package_name]
type = "String"
name = "Main Package Name"
description = """
The name of the main package being run.
Defaults to \"Ambient\"."""
attributes = ["Debuggable", "Resource"]

[components.selectable]
type = "Empty"
name = "Selectable"
description = "If attached, this object can be selected in the editor."
attributes = ["Debuggable", "Networked", "Store"]

[components.snap_to_ground]
type = "F32"
name = "Snap to ground"
description = """
This object should automatically be moved with the terrain if the terrain is changed.
The value is the offset from the terrain."""
attributes = ["Debuggable", "Networked", "Store"]

[components.tags]
type = { type = "Vec", element_type = "String" }
name = "Tags"
description = "Tags for categorizing this entity."
attributes = ["Debuggable", "Networked", "Store"]

[components.ui_scene]
type = "Empty"
name = "UI scene"
description = "If attached, this entity belongs to the UI scene."
attributes = ["Debuggable", "Networked", "Store"]

[components.window_logical_size]
type = "Uvec2"
name = "Window logical size"
description = "The logical size is the physical size divided by the scale factor."
attributes = ["MaybeResource", "Debuggable", "Networked"]

[components.window_physical_size]
type = "Uvec2"
name = "Window physical size"
description = "The physical size is the actual number of pixels on the screen."
attributes = ["MaybeResource", "Debuggable", "Networked"]

[components.window_scale_factor]
type = "F64"
name = "Window scale factor"
description = """
The DPI/pixel scale factor of the window.
On standard displays, this is 1, but it can be higher on high-DPI displays like Apple Retina displays."""
attributes = ["MaybeResource", "Debuggable", "Networked"]

[components.ref_count]
type = "U32"
name = "Reference count"
description = "Ref-counted enity. If this entity doesn't have a `parent` component, and the ref count reaches 0, it will be removed together with all its children recursively."
attributes = ["MaybeResource", "Debuggable", "Networked"]
