[package]
name = "Audio"
description = "Audio functionality and state."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2024-01-03"
ambient_version = "0.3.2-nightly-2024-01-03"

[components.is_audio_player]
type = "Empty"
name = "Is audio player"
description = "The entity is an audio player."
attributes = ["MaybeResource", "Debuggable"]

[components.is_spatial_audio_player]
type = "Empty"
name = "Is spatial audio player"
description = "The entity is a spatial audio player."
attributes = ["MaybeResource", "Debuggable"]

[components.spatial_audio_emitter]
type = "EntityId"
name = "Spatial audio emitter"
description = "The entity is a spatial audio emitter."
attributes = ["MaybeResource", "Debuggable"]

[components.spatial_audio_listener]
type = "EntityId"
name = "Spatial audio listener"
description = "The entity is a spatial audio listener."
attributes = ["MaybeResource", "Debuggable"]

[components.looping]
type = "Bool"
name = "Looping"
description = """
Whether or not the audio should loop.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.onepole_lpf]
type = "F32"
name = "One pole low pass filter"
description = """
With this component, the audio will be filtered with a one pole low pass filter.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.playing_sound]
type = "Empty"
name = "Playing sound"
description = """
The entity with this comp is a playing sound.
We can attach other components to it to control the sound parameters.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.amplitude]
type = "F32"
name = "Amplitude"
description = """
The amplitude of the audio.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.panning]
type = "F32"
name = "Panning"
description = """
The panning of the audio.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.lpf]
type = "Vec2"
name = "Low_pass filter"
description = """
Low pass filter. The first value is the cutoff frequency, the second is the bandwidth.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.hpf]
type = "Vec2"
name = "High_pass filter"
description = """
High pass filter. The first value is the cutoff frequency, the second is the bandwidth.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.audio_url]
type = "String"
name = "Audio URL"
description = """
The URL of the assets.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.play_now]
type = "Empty"
name = "Trigger at this frame"
description = """
The system will watch for this component and PLAY the audio at this frame,
using the other components as parameters.
Then set it back to false.
"""
attributes = ["MaybeResource", "Debuggable"]

[components.stop_now]
type = "Empty"
name = "Stop at this frame"
description = """
The system will watch for this component and STOP the audio at this frame,
using the other components as parameters.
Then set it back to false.
"""
attributes = ["MaybeResource", "Debuggable"]
