[package]
name = "Entity Component System"
description = "Core components for the ECS and entities."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-12-17"
ambient_version = "0.3.2-nightly-2023-12-17"

[components.dont_despawn_on_unload]
type = "Empty"
name = "Don't automatically despawn on module unload"
description = "Indicates that this entity shouldn't be despawned when the module that spawned it unloads."
attributes = ["Debuggable", "Store"]

[components.dont_store]
type = "Empty"
name = "Don't store"
description = "Indicates that this entity shouldn't be stored on disk."
attributes = ["Debuggable", "Networked", "Store"]

[components.id]
type = "EntityId"
name = "ID"
description = "The ID of the entity."
attributes = ["Debuggable", "Networked", "Store"]

[components.remove_at_game_time]
type = "Duration"
name = "Remove at game time"
description = "If attached, this entity will be despawned at the specified game time."
attributes = ["Debuggable"]
