[package]
name = "Hierarchy"
description = "Parent/child relationships."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-12-07"
ambient_version = "0.3.2-nightly-2023-12-07"

[components.parent]
type = "EntityId"
name = "Parent"
description = "The parent of this entity."
attributes = ["Debuggable", "Networked", "Store"]

[components.children]
type = { type = "Vec", element_type = "EntityId" }
name = "Children"
description = "The children of this entity."
attributes = ["Debuggable", "Store", "MaybeResource"]

[components.unmanaged_children]
type = "Empty"
name = "Unmanaged children"
description = "This children component is not updated automatically for this entity when this component is attached."
attributes = ["Debuggable", "Networked", "Store", "MaybeResource"]
