[package]
name = "Input"
description = "Mouse, keyboard and controller input."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-11-28"
ambient_version = "0.3.2-nightly-2023-11-28"

[components.mouse_over_entity]
type = "EntityId"
name = "Mouse over entity"
description = "The entity the mouse is currently over."
attributes = ["Debuggable", "Resource"]

[components.mouse_over_distance]
type = "F32"
name = "Mouse over distance"
description = "This distance to the entity that the mouse is currently over."
attributes = ["Debuggable", "Resource"]

[components.is_mouse_over]
type = "U32"
name = "Mouse over"
description = "The number of mouse cursors that are currently over this entity."
attributes = ["Debuggable"]

[components.mouse_pickable_max]
type = "Vec3"
name = "Mouse pickable max"
description = "This entity can be clicked by the mouse, and this component defines the max AABB bound of the click area."
attributes = ["Debuggable", "Networked", "Store"]

[components.mouse_pickable_min]
type = "Vec3"
name = "Mouse pickable min"
description = "This entity can be clicked by the mouse, and this component defines the min AABB bound of the click area."
attributes = ["Debuggable", "Networked", "Store"]


[messages.MouseOverChanged]
description = "Mouse over has been updated"
fields = { from_external = "Bool", mouse_over = "EntityId", distance = "F32" }
as_module_message = true

[messages.ClipboardGet]
description = "Sent to a package that has requested the clipboard contents."
fields = { contents = { container_type = "Option", element_type = "String" } }
