[package]
name = "Layout"
description = "Layout components such as flow, margins etc."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2024-01-03"
ambient_version = "0.3.2-nightly-2024-01-03"

[components.align_horizontal]
type = "Align"
name = "Align horizontal"
description = "Layout alignment: horizontal."
attributes = ["Debuggable", "Networked", "Store"]

[components.align_vertical]
type = "Align"
name = "Align vertical"
description = "Layout alignment: vertical."
attributes = ["Debuggable", "Networked", "Store"]

[components.docking]
type = "Docking"
name = "Docking"
description = "Layout docking."
attributes = ["Debuggable", "Networked", "Store"]

[components.fit_horizontal]
type = "Fit"
name = "Fit horizontal"
description = "Layout fit: horizontal."
attributes = ["Debuggable", "Networked", "Store"]

[components.fit_vertical]
type = "Fit"
name = "Fit vertical"
description = "Layout fit: vertical."
attributes = ["Debuggable", "Networked", "Store"]

[components.layout]
type = "Layout"
name = "Layout"
description = "Layout."
attributes = ["Debuggable", "Networked", "Store"]

[components.orientation]
type = "Orientation"
name = "Orientation"
description = "Layout orientation."
attributes = ["Debuggable", "Networked", "Store"]

[components.is_book_file]
type = "Empty"
name = "Is book file"
description = "This is a file in a `layout_bookcase`."
attributes = ["Debuggable", "Networked", "Store"]

[components.margin]
type = "Vec4"
name = "Margin"
description = "Layout margin: [top, right, bottom, left]."
attributes = ["Debuggable", "Networked", "Store"]

[components.padding]
type = "Vec4"
name = "Padding"
description = "Layout padding: [top, right, bottom, left]."
attributes = ["Debuggable", "Networked", "Store"]

[components.mesh_to_local_from_size]
type = "Empty"
name = "Mesh to local from size"
description = "Update the `mesh_to_local` based on the width and height of this entity."
attributes = ["Debuggable", "Networked", "Store"]

[components.min_height]
type = "F32"
name = "Minimum height"
description = "The minimum height of a UI element."
attributes = ["Debuggable", "Networked", "Store"]

[components.min_width]
type = "F32"
name = "Minimum width"
description = "The minimum width of a UI element."
attributes = ["Debuggable", "Networked", "Store"]

[components.max_height]
type = "F32"
name = "Maximum height"
description = "The maximum height of a UI element."
attributes = ["Debuggable", "Networked", "Store"]

[components.max_width]
type = "F32"
name = "Maximum width"
description = "The maximum width of a UI element."
attributes = ["Debuggable", "Networked", "Store"]

[components.is_screen]
type = "Empty"
name = "Is screen"
description = "This entity will be treated as a screen. Used by the Screen ui component."
attributes = ["Debuggable", "Networked", "Store"]

[components.space_between_items]
type = "F32"
name = "Space between items"
description = "Space between items in a layout."
attributes = ["Debuggable", "Networked", "Store"]

[components.width]
type = "F32"
name = "Width"
description = "The width of a UI element."
attributes = ["Debuggable", "Networked", "Store"]

[components.height]
type = "F32"
name = "Height"
description = "The height of a UI element."
attributes = ["Debuggable", "Networked", "Store"]

[components.gpu_ui_size]
type = "Vec4"
name = "GPU UI size"
description = "Upload the width and height of this UI element to the GPU."
attributes = ["Debuggable", "Networked", "Store"]

[enums.Align]
description = "Layout alignment."
[enums.Align.members]
Begin = "Begin"
Center = "Center"
End = "End"

[enums.Fit]
description = "Layout fit."
[enums.Fit.members]
None = "None"
Parent = "Parent"
Children = "Children"

[enums.Orientation]
description = "Layout orientation."
[enums.Orientation.members]
Horizontal = "Horizontal"
Vertical = "Vertical"

[enums.Docking]
description = "The edge to dock to."
[enums.Docking.members]
Left = "Left"
Right = "Right"
Top = "Top"
Bottom = "Bottom"
Fill = "Fill"

[enums.Layout]
description = "The type of the layout to use."
[enums.Layout.members]
Flow = "Bottom-up flow layout."
Dock = "Top-down dock layout."
Bookcase = "Min-max bookcase layout."
WidthToChildren = "Width to children."
