[package]
name = "Network"
description = "Network-related state."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-11-27"
ambient_version = "0.3.2-nightly-2023-11-27"

[components.is_remote_entity]
type = "Empty"
name = "Is remote entity"
description = "If attached, this entity was not spawned locally (e.g. if this is the client, it was spawned by the server)."
attributes = ["Debuggable", "Networked"]

[components.is_persistent_resources]
type = "Empty"
name = "Is persistent resources"
description = "If attached, this entity contains global resources that are persisted to disk and synchronized to clients."
attributes = ["Debuggable", "Networked"]

[components.is_synced_resources]
type = "Empty"
name = "Is synchronized resources"
description = "If attached, this entity contains global resources that are synchronized to clients, but not persisted."
attributes = ["Debuggable", "Networked"]

[components.no_sync]
type = "Empty"
name = "No sync"
description = "If attached, this entity will not be synchronized to clients."
attributes = ["Debuggable", "Networked", "Store"]
