[package]
name = "Player"
description = "Components that are attached to player entities."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-12-04"
ambient_version = "0.3.2-nightly-2023-12-04"

[components.local_user_id]
type = "String"
name = "Local user ID"
description = "The user ID of the local player."
attributes = ["Debuggable", "Networked", "Resource", "Store"]

[components.is_player]
type = "Empty"
name = "Is player"
description = """
This entity is a player.
Note that this is a logical construct; a player's body may be separate from the player itself."""
attributes = ["Debuggable", "Networked", "Store"]

[components.user_id]
type = "String"
name = "User ID"
description = """
An identifier attached to all things owned by a user, and supplied by the user.
This can be attached to more than just the player; by convention, it is also attached to related entities, including their camera and body."""
attributes = ["Debuggable", "Networked", "Store"]
