[package]
name = "Prefab"
description = "Prefab-related state, including loading of prefabs."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-12-30"
ambient_version = "0.3.2-nightly-2023-12-30"

[components.prefab_from_url]
type = "String"
name = "Prefab from URL"
description = """
Load and attach a prefab from a URL or relative path.
When loaded, the components from this prefab will add to or replace the existing components for the entity."""
attributes = ["Debuggable", "Store"]

[components.spawned]
type = "Empty"
name = "Spawned"
description = "If attached, this entity was built from a prefab that has finished spawning."
attributes = ["Debuggable"]
