[package]
name = "Procedurals"
description = "Procedural asset functionality and related."
content = { type = "Asset", schema = true }
version = "0.3.2-nightly-2023-12-15"
ambient_version = "0.3.2-nightly-2023-12-15"

[components.procedural_mesh]
type = "ProceduralMeshHandle"
name = "Procedural mesh"
description = "Attaches a procedural mesh to this entity"
attributes = ["Debuggable", "Store"]

[components.procedural_material]
type = "ProceduralMaterialHandle"
name = "Procedural material"
description = "Attaches a procedural material to this entity"
attributes = ["Debuggable", "Store"]
