[package]
name = "ambient_ecs_editor"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient ECS editor. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-12-15" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-15" }
ambient_ui_native = { path = "../ui_native" , version = "0.3.2-nightly-2023-12-15" }
ambient_layout = { path = "../layout" , version = "0.3.2-nightly-2023-12-15" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-12-15" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2023-12-15" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2023-12-15" }
env_logger = { workspace = true }
itertools = { workspace = true }
glam = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app", features = ["profile"] , version = "0.3.2-nightly-2023-12-15" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2023-12-15" }
tokio = { workspace = true }
