[package]
id = "ytdci6e6yiglca2d6awwpi2lt5h6sqvg"
name = "Primitives"
description = "Draw boxes, spheres and other basic shapes."
version = "0.3.2-nightly-2023-11-24"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/primitives"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera" , deployment = "5LYimSMVCEG1d8FIRz7yXj" }
