[package]
name = "ambient_decals"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient decals. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_asset_cache = { path = "../asset_cache" , version = "0.3.2-nightly-2023-12-25" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2023-12-25" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2023-12-25" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2023-12-25" }
ambient_gpu_ecs = { path = "../gpu_ecs" , version = "0.3.2-nightly-2023-12-25" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-25" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2023-12-25" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2023-12-25" }
tracing = { workspace = true }
glam = { workspace = true }

[dev-dependencies]
ambient_app = { path = "../app" , version = "0.3.2-nightly-2023-12-25" }
ambient_element = { path = "../../shared_crates/element" , version = "0.3.2-nightly-2023-12-25" }
ambient_primitives = { path = "../primitives" , version = "0.3.2-nightly-2023-12-25" }
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2023-12-25" }
env_logger = { workspace = true }

[features]
hotload-includes = [
    'ambient_native_std/hotload-includes',
    'ambient_renderer/hotload-includes',
    'ambient_gpu/hotload-includes',
]
