[package]
name = "ambient_package_semantic_native"
description = "Glues together the package semantic system and other native code, like asset loading."
edition = "2021"
version.workspace = true
rust-version.workspace = true

[dependencies]
ambient_ecs = { path = "../ecs", version = "0.3.2-nightly-2023-12-25" }
ambient_native_std = { path = "../native_std", version = "0.3.2-nightly-2023-12-25" }
ambient_network = { path = "../network", version = "0.3.2-nightly-2023-12-25" }
ambient_core = { path = "../core", version = "0.3.2-nightly-2023-12-25" }

ambient_cb = { path = "../../libs/cb", version = "0.3.2-nightly-2023-12-25" }

ambient_package = { path = "../../shared_crates/package", version = "0.3.2-nightly-2023-12-25" }
ambient_package_semantic = { path = "../../shared_crates/package_semantic", version = "0.3.2-nightly-2023-12-25" }
ambient_shared_types = { path = "../../shared_crates/shared_types", version = "0.3.2-nightly-2023-12-25" }

anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
