[package]
id = "afl5yv5ya35vbuaj3aido22cwjzat25z"
name = "Unit"
description = "Schema for units in games. Often used with the Game Object schema."
version = "0.3.2-nightly-2023-11-24"
content = { type = "Asset", schema = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[dependencies]
game_object = { path = "../game_object", deployment = "TFYhFc5wKkplokwUm1uQN" }

[components]
run_direction = { type = "Vec2", attributes = ["Debuggable", "Networked"] }
speed = { type = "F32", description = "The speed the unit can walk at", attributes = [
    "Debuggable",
    "Networked",
] }
run_speed_multiplier = { type = "F32", description = "The speed the unit can run at", attributes = [
    "Debuggable",
    "Networked",
] }
strafe_speed_multiplier = { type = "F32", description = "The speed the unit can strafe at", attributes = [
    "Debuggable",
    "Networked",
] }
air_speed_multiplier = { type = "F32", description = "When the unit is in the air; how much can it control its movement? If this is 0, it can't control it at all. If it's 1 it's the same as on the ground.", attributes = [
    "Debuggable",
    "Networked",
] }
unit_displacement = { type = "Vec3", attributes = [
    "Debuggable",
    "Networked",
], description = "The distance the unit tried to move last frame (though it may have collided so the actual distance may be shorter)." }

jumping = { type = "Bool", attributes = ["Debuggable", "Networked"] }
running = { type = "Bool", attributes = ["Debuggable", "Networked"] }
shooting = { type = "Bool", attributes = ["Debuggable", "Networked"] }

vertical_velocity = { type = "F32", name = "Unit vertical speed", description = "The units's vertical speed.", attributes = [
    "Debuggable",
    "Networked",
] }
is_on_ground = { type = "Bool", attributes = ["Debuggable", "Networked"] }

head_ref = { type = "EntityId", attributes = ["Debuggable", "Networked"] }
