[package]
id = "xq7xenkzhaefhpt2wp7wrcsrwvxziyjm"
name = "Raw Text"
description = "Draw 2D text in 3D."
version = "0.3.2-nightly-2024-01-03"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/raw_text"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-03"
