[package]
id = "ucrvg2az42ep6ge43ewuz6mqkvmvcxdb"
name = "Screens"
description = "Demonstration of screens/pages. Useful for a lobby screen, loading screen or such."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/screens"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
