[package]
id = "u5bpyalmmxsdsnlwfnamh7kvxjfodvh7"
name = "Scroll area"
description = "Use the mouse wheel to reveal more content."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/scroll"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
