[package]
id = "mnm43qv33k7kx235bz5hcgoguokwxzwo"
name = "Tangent Behavior: Vehicle"
description = "Implements the vehicle behavior for Tangent."
version = "0.3.2-nightly-2023-11-23"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2023-11-23"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", deployment = "5Dxfql36E5hkktqsE0Eabx" }
game_object = { path = "../../../../schemas/game_object", deployment = "TFYhFc5wKkplokwUm1uQN" }
kenney_impact_sounds = { path = "../../../../assets/kenney_impact_sounds", deployment = "Rs2MDxuzMydleCCHlEHx8" }
explosion = { path = "../../../../std/explosion", deployment = "I4BxHahNN25JhluFbLJ6z" }

[messages.OnCollision]
name = "On Collision"
description = "Sent to the client when a vehicle collides with something."
fields = { position = "Vec3", speed = "F32", vehicle_id = "EntityId" }
