
[package]
name = "ambient_gpu"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient GPU functionality. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys", version = "0.3.2-nightly-2023-11-28" }
ambient_native_std = { path = "../native_std", version = "0.3.2-nightly-2023-11-28" }
ambient_settings = { path = "../settings", version = "0.3.2-nightly-2023-11-28" }

ambient_std = { path = "../../shared_crates/std", version = "0.3.2-nightly-2023-11-28" }

aho-corasick = { workspace = true }
bytemuck = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
glam = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
byteorder = { workspace = true }
image = { workspace = true }
itertools = { workspace = true }
ndarray = { workspace = true }
ordered-float = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
parking_lot = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
cfg-if = { workspace = true }

[features]
hotload-includes = ['ambient_native_std/hotload-includes']


[target.'cfg(target_os = "unknown")'.dev-dependencies]
# TODO: use provided webgpu api when released
wgpu = { version = "0.15", features = ["webgl"] }
