[package]
id = "x2zcchov26324tx3av4jvrl5xxealush"
name = "Basic model loading"
description = "Load and render a glb model."
version = "0.3.2-nightly-2023-11-24"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/basic_model"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "2o485Le57deXsEYhFu4lmf" }
