[package]
id = "itzh3wovmdje4ttrmo6wrravaaxp6b52"
name = "Tangent Core"
description = "The core of Tangent. The connective glue between all the other packages. (Will likely be split up.)"
version = "0.3.2-nightly-2023-11-23"
content = { type = "Asset", code = true }
authors = ["philpax"]
ambient_version = "0.3.2-nightly-2023-11-23"

[dependencies]
tangent_schema = { path = "../../schema", deployment = "5Dxfql36E5hkktqsE0Eabx" }

game_object = { path = "../../../../schemas/game_object", deployment = "TFYhFc5wKkplokwUm1uQN" }
unit_schema = { path = "../../../../schemas/unit", deployment = "hfv4W9UuED197vKDfol7g" }

explosion = { path = "../../../../std/explosion", deployment = "I4BxHahNN25JhluFbLJ6z" }
nameplates = { path = "../../../../std/nameplates", deployment = "72DSQZF3Epi0GCy9JUmnAh" }

kenney_impact_sounds = { path = "../../../../assets/kenney_impact_sounds", deployment = "Rs2MDxuzMydleCCHlEHx8" }

[messages.Input]
name = "Input"
description = "Input"
[messages.Input.fields]
direction = "Vec2"
jump = "Bool"
fire = "Bool"
use_button = "Bool"
sprint = "Bool"
respawn = "Bool"
aim_direction = "Vec2"
# Let's not trust the client in the future
aim_ray_origin = "Vec3"
aim_ray_direction = "Vec3"

[messages.UseFailed]
name = "Use Failed"
description = "Sent from the server to the client when a use action fails."
fields = {}
