[package]
id = "s37z23uqis7ts6ya7v2f66ni23m3upt7"
name = "Visualize Colliders"
description = "Visualize the colliders of a scene."
version = "0.3.2-nightly-2023-11-25"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-25"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
