[package]
id = "znidkp3d3rqx7ir7bvs2ahx4sfrr2n7n"
name = "Skinmesh"
description = "Render a character model with animations."
version = "0.3.2-nightly-2023-11-23"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/skinmesh"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-23"

[messages]
SetController = { name = "Set controller", description = "Sets the animation controller.", fields = { value = "U32" } }

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
