[package]
id = "llhdryqkfsr6gy4f26wbolh4kfwnzn3c"
name = "Kenney's Space Kit"
authors = ["Kenney"]
description = "https://www.kenney.nl/assets/space-kit for Ambient. (Uploaded by Ambient, not Kenney.)"
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", models = true }
ambient_version = "0.3.2-nightly-2023-11-27"
