[package]
name = "ambient_water"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient water. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2024-01-06" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2024-01-06" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2024-01-06" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2024-01-06" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2024-01-06" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2024-01-06" }
ambient_primitives = { path = "../primitives" , version = "0.3.2-nightly-2024-01-06" }
ambient_sky = { path = "../sky" , version = "0.3.2-nightly-2024-01-06" }
wgpu = { workspace = true }
glam = { workspace = true }
