[package]
name = "ambient_settings"
edition = "2021"
version = { workspace = true }
rust-version = { workspace = true }
description = "Ambient runtime settings"
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_native_std = { path = "../native_std", version = "0.3.2-nightly-2023-12-27" }

ambient_dirs = { path = "../../shared_crates/dirs", version = "0.3.2-nightly-2023-12-27" }

anyhow = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
cfg-if = { workspace = true }

[target.'cfg(target_os = "unknown")'.dependencies]
web-sys = { version = "0.3" }
js-sys = { version = "0.3" }
