[package]
id = "ie4hdvkvui6t36yzniyex2hc5i2bradc"
name = "Third-person camera"
description = "A simple third-person camera controller."
version = "0.3.2-nightly-2023-11-23"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/third_person_camera"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-23"

[dependencies]
base_assets = { path = "../../../packages/std/base_assets", deployment = "8HCtBKdJiEHCrSR52iTRZ" }
third_person_controller = { path = "../../../packages/std/third_person_controller", deployment = "1jLWOZQ6qmcudYIL93e2Le" }
character_animation = { path = "../../../packages/std/character_animation", deployment = "1gJ1BGZMYz2k6SQwHVONG4" }
hide_cursor = { path = "../../../packages/std/hide_cursor", deployment = "2weRubPIURz10C4RYS2Vdv" }
nameplates = { path = "../../../packages/std/nameplates", deployment = "72DSQZF3Epi0GCy9JUmnAh" }
