[package]
name = "ambient_layout"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient UI layouting functionality. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2024-01-06" }
ambient_gpu_ecs = { path = "../gpu_ecs" , version = "0.3.2-nightly-2024-01-06" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2024-01-06" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2024-01-06" }
ambient_input = { path = "../input" , version = "0.3.2-nightly-2024-01-06" }
glam = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
profiling = { workspace = true }
