[package]
id = "xr6whcy65gn3vlzrp2ssyn7udcbxb6mu"
name = "Editor [WIP]"
description = "An extremely early basic sketch of a level editor."
version = "0.3.2-nightly-2023-11-25"
content = { type = "Tool" }
ambient_version = "0.3.2-nightly-2023-11-25"

[dependencies]
editor_schema = { path = "../../schemas/editor", deployment = "1GPXgGyaz1DM3k2h7QOYPP" }
hide_cursor = { path = "../../std/hide_cursor", enabled = false, deployment = "2weRubPIURz10C4RYS2Vdv" }

[components]
# Player components
editor_camera = { type = "EntityId", attributes = ["Networked", "Debuggable"] }
mouseover_position = { type = "Vec3", attributes = ["Networked", "Debuggable"] }
mouseover_entity = { type = "EntityId", attributes = [
    "Networked",
    "Debuggable",
] }
selected_entity = { type = "EntityId", attributes = [
    "Networked",
    "Debuggable",
] }

has_sample_scene = { type = "Empty", attributes = [
    "Networked",
    "MaybeResource",
] }

# Camera components
camera_angle = { type = "Vec2", description = "X is yaw, Y is pitch", attributes = [
    "Networked",
    "Debuggable",
] }

[messages.ToggleEditor.fields]
camera_transform = { container_type = "Option", element_type = "Mat4" }

[messages.Input.fields]
aim_delta = "Vec2"
movement = "Vec2"
boost = "Bool"

ray_origin = "Vec3"
ray_direction = "Vec3"
select = "Bool"
freeze = "Bool"
translate_to = { type = "Option", element_type = "Vec3" }
