[package]
id = "jkr622pbesmaaco76bjc6ll6v4t4lajh"
name = "Screen Ray"
description = "Intersect a ray from the screen with the world."
version = "0.3.2-nightly-2023-11-24"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/screen_ray"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-24"

[messages.Input.fields]
ray_origin = "Vec3"
ray_dir = "Vec3"
spawn = "Bool"

[components.player_cube_ref]
name = "Player Cube Ref"
description = "Attached to the player; references the preview cube the player is controlling."
type = "EntityId"
attributes = ["Networked", "Debuggable"]

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera", deployment = "5LYimSMVCEG1d8FIRz7yXj" }
