[package]
id = "mkd4mhans4bdn3mvmt45vxqbxepdhys3"
name = "Tangent Camera: Follow"
description = "Implements a follow camera for vehicles."
version = "0.3.2-nightly-2024-01-07"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2024-01-07"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", deployment = "5Dxfql36E5hkktqsE0Eabx" }
