
[package]
name = "ambient_meshes"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient meshes. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2023-12-28" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2023-12-28" }
glam = { workspace = true }
serde = { workspace = true }
