[package]
name = "ambient_wasm"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_sys = { path = "../sys" , version = "0.3.2-nightly-2024-01-02" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2024-01-02" }
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2024-01-02" }
ambient_input = { path = "../input" , version = "0.3.2-nightly-2024-01-02" }
ambient_network = { path = "../network" , version = "0.3.2-nightly-2024-01-02" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2024-01-02" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2024-01-02" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2024-01-02" }
ambient_procedurals = { path = "../procedurals" , version = "0.3.2-nightly-2024-01-02" }
ambient_package_semantic_native = { path = "../package_semantic_native" , version = "0.3.2-nightly-2024-01-02" }

ambient_shared_types = { path = "../../shared_crates/shared_types", features = [
    "native",
] , version = "0.3.2-nightly-2024-01-02" }

anyhow = { workspace = true }
async-trait = { workspace = true }
byteorder = { workspace = true }
bytes = { workspace = true }
data-encoding = { workspace = true }
flume = { workspace = true }
glam = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
paste = { workspace = true }
profiling = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
slotmap = { workspace = true }
tokio = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
ulid = { workspace = true }
wit-component = { workspace = true }
futures = { workspace = true }

wasm-bridge = { git = "https://github.com/AmbientRun/wasm-bridge", branch  = "wasmtime-git", version = "0.2", features = [
    "component-model",
    "sync",
    "wasi",
] }


[target.'cfg(windows)'.build-dependencies]
dunce = "1.0"

[build-dependencies]
ambient_package_macro_common = { path = "../../shared_crates/package_macro_common" , version = "0.3.2-nightly-2024-01-02" }
ambient_sys = { path = "../sys" , version = "0.3.2-nightly-2024-01-02" }
ambient_std = { path = "../../shared_crates/std" , version = "0.3.2-nightly-2024-01-02" }
wit-bindgen-core = { workspace = true }
wit-bindgen-rust = { workspace = true }
ambient_prefab = { path = "../prefab" , version = "0.3.2-nightly-2024-01-02" }

[target.'cfg(target_os = "unknown")'.dependencies]
wasm-bridge-js = { git = "https://github.com/AmbientRun/wasm-bridge", branch = "wasmtime-git", version = "0.2", features = [
    "component-model",
    "wasi",
] }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
# NOTE: accessible through `wasm-bridge`. This is used to enforce specific features on the `wasmtime` crate
wasi-cap-std-sync = { workspace = true }

wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }

ambient_physics = { path = "../physics" , version = "0.3.2-nightly-2024-01-02" }
physxx = { path = "../../libs/physxx" , version = "0.3.2-nightly-2024-01-02" }

[features]
debug-local-datagram-latency = []
