[package]
id = "devasx4mng2jjjaw65mmicqc45rngafa"
name = "Transparency"
description = "Draw translucent objects."
version = "0.3.2-nightly-2024-01-20"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/basics/transparency"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2024-01-20"

[dependencies]
orbit_camera = { path = "../../../packages/std/orbit_camera" , deployment = "5LYimSMVCEG1d8FIRz7yXj" }
