[package]
id = "xar372tfo2oswb4pkvx7h7o3rxi6tap6"
name = "Hide Cursor"
description = "Locks and hides the cursor when no UI element is in focus, with the Escape key enabling focus reset."
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2023-11-27"
