[package]
name = "ambient_sky"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Ambient sky. Host-only."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ambient_ecs = { path = "../ecs" , version = "0.3.2-nightly-2024-01-04" }
ambient_native_std = { path = "../native_std" , version = "0.3.2-nightly-2024-01-04" }
ambient_core = { path = "../core" , version = "0.3.2-nightly-2024-01-04" }
ambient_gpu = { path = "../gpu" , version = "0.3.2-nightly-2024-01-04" }
ambient_gizmos = { path = "../gizmos" , version = "0.3.2-nightly-2024-01-04" }
ambient_meshes = { path = "../meshes" , version = "0.3.2-nightly-2024-01-04" }
ambient_renderer = { path = "../renderer" , version = "0.3.2-nightly-2024-01-04" }
wgpu = { workspace = true }
noise = { workspace = true }
glam = { workspace = true }
bytemuck = { workspace = true }
derive_more = { workspace = true }
ordered-float = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
ambient_cameras = { path = "../cameras" , version = "0.3.2-nightly-2024-01-04" }
tokio = { workspace = true }

[features]
hotload-includes = ['ambient_native_std/hotload-includes']
