[package]
id = "e4unr4x2lz2ov7dsd5vnjylbykwixvv2"
name = "Kenney's Impact Sounds"
authors = ["Kenney"]
description = "https://www.kenney.nl/assets/impact-sounds for Ambient. (Uploaded by Ambient, not Kenney.)"
version = "0.3.2-nightly-2023-11-27"
content = { type = "Asset", audio = true }
ambient_version = "0.3.2-nightly-2023-11-27"
