[package]
id = "n3xokyl3yn4vd3lzfjlvbbtgnnmqlnjo"
name = "Rectangle"
description = "A rectangle with a border, rounded corners and a background color."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/rect"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
