[package]
name = "ambient_package"
edition = "2021"
description = "Definition of the Ambient package manifest format."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"

ambient_shared_types = { path = "../shared_types", version = "0.3.2-nightly-2023-12-31" }

serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
indexmap = { workspace = true }
convert_case = { workspace = true }
once_cell = { workspace = true }
url = { workspace = true }
chrono = { workspace = true }
semver = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
data-encoding = { workspace = true }

[dev-dependencies]
paste = { workspace = true }
serde_json = { workspace = true }
