[package]
id = "fsv4zmeyotsu4lhji4rv6kivla5vmifi"
name = "Clock"
description = "A 2D clock example."
version = "0.3.2-nightly-2023-11-27"
repository = "https://github.com/AmbientRun/Ambient/tree/main/guest/rust/examples/ui/clock"
type = "Game"
content = { type = "Playable", example = true }
ambient_version = "0.3.2-nightly-2023-11-27"
