# This workflow is triggered on demand and publishes the API.

name: Publish API

on:
  workflow_dispatch: {}

jobs:
  publish-api:
    runs-on: ubuntu-22.04
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add --toolchain stable wasm32-wasi
      - name: Release all packages required for API
        run: cargo campfire-slim release publish --execute
