[package]
id = "jyp2hh3fpjfe7kaos36zbdztfypqip3m"
name = "Tangent Gun: Laser"
description = "Implements laser guns."
version = "0.3.2-nightly-2023-11-25"
content = { type = "Asset", code = true }
ambient_version = "0.3.2-nightly-2023-11-25"
authors = ["philpax"]

[dependencies]
tangent_schema = { path = "../../schema", deployment = "5Dxfql36E5hkktqsE0Eabx" }
kenney_space_kit = { path = "../../../../assets/kenney_space_kit", deployment = "2nSAjXKZ4c0p5Y57NVrNbP" }
kenney_digital_audio = { path = "../../../../assets/kenney_digital_audio", deployment = "1sBS8todVINgBibbhBqDXm" }

explosion = { path = "../../../../std/explosion", deployment = "I4BxHahNN25JhluFbLJ6z" }

[components]
is_gun_laser = { type = "Empty", name = "Is Gun (Laser)", description = "This entity is a laser gun." }
damage = { type = "F32", name = "Damage", description = "The amount of damage this gun does." }
time_between_shots = { type = "Duration", name = "Time Between Shots", description = "The amount of time between shots." }
last_shot_time = { type = "Duration", name = "Last Shot Time", description = "The time of the last shot." }

[concepts.GunLaser]
name = "Gun Laser"
description = "A laser gun."
extends = ["ambient_core::transform::Transformable"]
[concepts.GunLaser.components.required]
is_gun_laser = {}
damage = {}
time_between_shots = {}
[concepts.GunLaser.components.optional]
last_shot_time = {}

[messages.Fire]
description = "Sent to the client-side when a gun is fired."
[messages.Fire.fields]
weapon_id = "EntityId"
