[package]
name = "ambient_package_macro_common"
version = { workspace = true }
rust-version = { workspace = true }
edition = "2021"
description = "Common implementation of a proc-macro that generates boilerplate from an `ambient.toml`."
license = "MIT OR Apache-2.0"
repository = "https://github.com/AmbientRun/Ambient"

[dependencies]
anyhow = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
syn = { workspace = true }
proc-macro2 = { workspace = true }
glam = { workspace = true }

ambient_package = { path = "../package" , version = "0.3.2-nightly-2024-01-09" }
ambient_package_semantic = { path = "../package_semantic" , version = "0.3.2-nightly-2024-01-09" }
ambient_shared_types = { path = "../shared_types" , version = "0.3.2-nightly-2024-01-09" }

[dev-dependencies]
indoc = "2.0"
